### ISSUE TITLE
Got an error while compiling the .ino file

### ISSUE THREAD

**Issue by ZanoDev** [125K/ESP8266_WiFi_Captive_Portal_2.0#1]
I wanted to change the SSID so I choose the .ino file instead of the .bin one.

Without touching the code, when I try to compile it i get this error:

```
In function 'String input(String)':

ESP8266_WiFi_Captive_Portal_2.0:31: error: no matching function for call to 'ESP8266WebServer::arg(String&)'

   String a=webServer.arg(argName);

                                 ^
```

How to solve this? I really think this project is cool, but apparently I need some help :(

**Comment by 125K** [comment]
Let me check your code
